version: '3'
services:
  nginx:
    image: nginx:1.27.2
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/usr/src/static/
    depends_on:
      - fastapi-app

  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs/:/usr/src/logs/
    environment:
      APP_ENV: ${APP_ENV}
      SECRET_KEY: ${SECRET_KEY}
      DB_URL: ${DB_URL}
