name: Django CI

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: Test Version
        default: 0.1.0
        required: true

jobs:
  test:
    name: TEST
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: db
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: CHECKOUT
      uses: actions/checkout@v4
    - name: SET UP PYTHON 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: INSTALL DEPENDENCIES
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync
    - name: RUN TEST
      run: |
        uv run coverage run -m pytest
        uv run coverage report

  docker:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: CHECKOUT
      uses: actions/checkout@v4
    - name: DOCKER META
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/weekending/weekend-api
    - name: SET UP DOCKER BUILDX
      uses: docker/setup-buildx-action@v3
    - name: LOGIN TO GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: BUILD AND PUSH DOCKER IMAGES
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
